### ISSUE TITLE
[Feedback]: Error codes not found

### ISSUE THREAD

**Issue by Bharatpahwa** [CosmoCloud/Bugs-and-Feedback#1]
**Feedback:**
Cannot find the Error Codes and How to resolve those Errors in the Documentation.
![Group 252](https://github.com/Cosmocloud/Bugs-and-Feedback/assets/102665650/1a1733ea-6ca9-4285-bfd3-2733d5fd2d43)

**Comment by shreybatra** [comment]
Hi @Bharatpahwa ! Thanks for reporting this. This error comes when we are unable to connect to your MongoDB Atlas database successfully.

Make sure - 
1. You have correctly created your Database secret with correct credentials (privatekey and publickey)
2. It gives a successful connection created notification.
3. Recreate the Secret again and check.

Let us know if this doesn't work.

**Comment by Bharatpahwa** [comment]
<img width="205" alt="image" src="https://github.com/Cosmocloud/Bugs-and-Feedback/assets/102665650/893ac07b-31b3-468c-9ee2-ba55b788d239">

It did connect successfully initially (Even with a different Database Name which was not present in MongoDB) but was giving that error while testing the API. It worked fine after deleting the secrets and connecting again (With DB name as present in MongoDB) OR by editing the DB name and it gave only id as a response.
Thanks for resolving the issue.

**Comment by shreybatra** [comment]
Thanks for confirming @Bharatpahwa ! MongoDB is a lazy database, so even it is a new database name, it will connect and create it upon the first insertion.
We will add more documentation and checks as well to inform this error much faster to the user.

Thank you, closing the issue.
